name: teach_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_colorpicker: ^1.1.0

  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  fl_chart: ^0.68.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  provider: ^6.1.2
  flutter_onboarding_slider: ^1.0.11
  firebase_database: ^11.0.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/categories/
    - assets/lottie/
    - assets/images/icons/
    - assets/images/topics/
    - assets/images/backgrounds/

